### ISSUE TITLE
Change photo orientation

### ISSUE THREAD

**Issue by djszutu** [ingojaeckel/go-raspberry-pi-timelapse#1]
Hi Ingo! Thanks for your work on this Pi Cam! Would it be possible to change the photo orientation so the photo is rotated 180 deg? It's easier for us to mount the camera if the camera cable comes out from the "top" of the camera rather than the bottom. As it's set up now, the camera cable comes out from the bottom of the camera.  Thank you! -Daphne

**Comment by ingojaeckel** [comment]
Great idea! Super simple. Will put it in over the next couple days!

**Comment by ingojaeckel** [comment]
Fixed in 741beeaa5730f81196e7fa2333b244dccfa1f0e2

**Comment by ingojaeckel** [comment]
@djszutu I do not have a pi available for testing at the moment. Do you mind fetching the latest executable and giving this a try? You should be able to select rotation & resolution in the current version, save the setting (it should persist between restarts of the pi), and the settings should be applied when taking pictures. But again, since I cannot test this with a real pi, there may be a few issues remaining.. Let me know & feel free to re-open this.
